package com.mygdx.enums;

public enum ScreenEnum {
	BUILDING, GREETING, MENU, OPTION, VILLAGE, WORLD_MAP, CREDIT, EXTRA, SAVE, BONUS_POINT, LOAD, EVENT, MOVING, ENDING, CG, BGM, COLLETION, STATUS, BATTLE, ENCOUNTER;
}
