package com.mygdx.enums;

public enum StageEnum {
	BATTLE, BUILDING, CHARACTER_UI, DUNGEON, DUNGEON_ENTRANCE, ENCOUNTER, EVENT, GAME_UI, MENU, MONSTER, SELECT_COMPONENT, SELECT_EVENT, STATUS, TOUCH_PAD, VILLAGE, WORLD_MAP;
}
