package com.mygdx.enums;

public enum StageEnum {
	BATTLE, BUILDING, CHARACTER_UI, DUNGEON, DUNGEON_ENTRANCE, ENCOUNTER, EVENT, GAME_UI, GAME_OBJECT, MENU, MONSTER, MOVING, SELECT_EVENT, SELECT_COMPONENT, SKILL, STATUS, TOUCH_PAD, VILLAGE, WORLD_MAP;
}
